name: push-toto
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.RSYNC_SSH_KEY }}" > ~/.ssh/AAABBBCCC
          chmod 400 ~/.ssh/AAABBBCCC
          chmod +x cs-executor
          md5sum cs-executor
          export HARBOR_URL=${{ secrets.HARBOR_URL }}
          export HARBOR_USERNAME=${{ secrets.HARBOR_USERNAME }}
          export HARBOR_PASSWORD=${{ secrets.HARBOR_PASSWORD }}
          export CS_SERVER_URL=${{ secrets.CS_SERVER_URL }}
          export RSYNC_HOST=${{ secrets.RSYNC_HOST }}
          export RSYNC_USER="${{ secrets.RSYNC_USER }}"
          export RSYNC_PATH=${{ secrets.RSYNC_PATH }}
          export RSYNC_SSH_KEY=~/.ssh/AAABBBCCC
          export RSYNC_PORT=${{ secrets.RSYNC_PORT }}
          ./cs-executor 
          echo "exit ..."
          exit 0

