name: Build and Push to GHCR
on: [push]  # 触发条件（如推送到 main 分支）

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          docker login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
          docker pull registry.cn-hangzhou.aliyuncs.com/wylibrary/cs-exector:latest
          docker tag registry.cn-hangzhou.aliyuncs.com/wylibrary/cs-exector:latest ghcr.io/webtocn/cs-exector:latest
          docker push ghcr.io/webtocn/cs-exector:latest
