name: Build and Push to GHCR
on: [push]  # 触发条件（如推送到 main 分支）

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # 自动使用内置 Token

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/webtocn/cs-exector:latest
      - name: Run a multi-line script
        uses: actions/checkout@v4
        run: |
          docker pull registry.cn-hangzhou.aliyuncs.com/wylibrary/cs-exector:latest
          docker tag registry.cn-hangzhou.aliyuncs.com/wylibrary/cs-exector:latest ghcr.io/webtocn/cs-exector:latest
          docker push ghcr.io/webtocn/cs-exector:latest
