name: toto-github 
on:
  schedule:
    - cron: '*/1 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          echo ${{ secrets.RSYNC_SSH_KEY }} > AAABBBCCC
          chmod 400 AAABBBCCC
          docker run --rm  -e BACKEND_URL=${{ secrets.BACKEND_URL }} -e RSYNC_HOST=${{ secrets.RSYNC_HOST }} -e RSYNC_PATH=${{ secrets.RSYNC_PATH }} -e RSYNC_SSH_KEY=./AAABBBCCC  -e RSYNC_PORT=${{ secrets.RSYNC_PORT }} registry.cn-hangzhou.aliyuncs.com/wylibrary/cs-exector:latest
          echo "exit ..."
